// <auto-generated />
namespace Gov.Dva.Ogc.Accreditation.Web.Mvc.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddWebForm21aReferenceAssociation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddWebForm21aReferenceAssociation));
        
        string IMigrationMetadata.Id
        {
            get { return "201310031634499_AddWebForm21aReferenceAssociation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
