//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gov.Dva.Ogc.Data.Accreditation.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebForm21Qualification
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> Form21ID { get; set; }
        public Nullable<bool> HasCompletedCourse { get; set; }
        public Nullable<bool> HasPassedExam { get; set; }
        public Nullable<bool> HasExperience { get; set; }
    
        public virtual WebForm21 WebForm21 { get; set; }
    }
}
