//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gov.Dva.Ogc.Data.Accreditation.Web.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebForm21aServiceBranch
    {
        public System.Guid Form21aID { get; set; }
        public Nullable<bool> IsArmy { get; set; }
        public Nullable<bool> IsNavy { get; set; }
        public Nullable<bool> IsAirForce { get; set; }
        public Nullable<bool> IsMarines { get; set; }
        public Nullable<bool> IsCoastGuard { get; set; }
        public Nullable<bool> IsNonVeteran { get; set; }
        public Nullable<bool> IsOther { get; set; }
        public string OtherService { get; set; }
    
        public virtual WebForm21a WebForm21a { get; set; }
    }
}
