//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gov.Dva.Ogc.Data.Accreditation.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebForm21
    {
        public WebForm21()
        {
            this.WebForm21OtherAccred = new HashSet<WebForm21OtherAccred>();
            this.WebForm21DischargeType = new HashSet<WebForm21DischargeType>();
            this.WebForm21Qualification = new HashSet<WebForm21Qualification>();
            this.WebForm21ServiceDate = new HashSet<WebForm21ServiceDate>();
        }
    
        public System.Guid Form21ID { get; set; }
        public string FormType { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string OrganizationName { get; set; }
        public Nullable<bool> IsGoodStanding { get; set; }
        public Nullable<bool> IsPaidMinRequirements { get; set; }
        public Nullable<bool> IsPaidAllRequirements { get; set; }
        public string WorkAddressLine1 { get; set; }
        public string WorkAddressLine2 { get; set; }
        public string WorkCity { get; set; }
        public string WorkState { get; set; }
        public string WorkZipCode { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
    
        public virtual ICollection<WebForm21OtherAccred> WebForm21OtherAccred { get; set; }
        public virtual WebForm21ServiceBranch WebForm21ServiceBranch { get; set; }
        public virtual ICollection<WebForm21DischargeType> WebForm21DischargeType { get; set; }
        public virtual ICollection<WebForm21Qualification> WebForm21Qualification { get; set; }
        public virtual ICollection<WebForm21ServiceDate> WebForm21ServiceDate { get; set; }
    }
}
