//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gov.Dva.Ogc.Data.Accreditation.Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebForm21aEmployer
    {
        public System.Guid ID { get; set; }
        public System.Guid Form21aID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string PhoneNo { get; set; }
        public string PositionTitle { get; set; }
        public Nullable<System.DateTime> DateRangeEmpBegin { get; set; }
        public Nullable<System.DateTime> DateRangeEmpEnd { get; set; }
        public string Supervisor { get; set; }
    
        public virtual WebForm21a WebForm21a { get; set; }
    }
}
