

var addServiceBranch = function () {
    //To add the HTML for a new row of military history, I'm taking the route of grabbing 
    //the autogenerated HTML from the .NET HtmlHelper for a row, 
    //incrementing the number by regex replacement, and appending it to the container div

    currCount = $(".serviceBranch").length; console.log('currCount=' + currCount);//count current # of serviceBranches
    var rowText = $(".servBranchRow").last().html();//get the last row of military service
    //increment collection number in HTML attributes
    r = "_" + (currCount - 1).toString() + "_"; //create regular expression text dynamically
    reg = new RegExp(r, "g");
    var nextRow = rowText.replace(reg, "_" + currCount.toString() + "_");
    
    r2 = "\\[" + (currCount - 1).toString() + "\\]"; //create regular expression text dynamically
    reg2 = new RegExp(r2, "g");
    nextRow = nextRow.replace(reg2, "[" + currCount.toString() + "]");
    
    if(currCount ==1){
        $("#serviceBranchDiv").append("<div class=\"row servBranchRow\">" + nextRow + "<div class=\"col-md-2 form-group\"><a href=\"#\" class=\"removeServiceBranch\">Remove</a></div></div>");
    }
    else {//assume > 1
        $("#serviceBranchDiv").append("<div class=\"row servBranchRow\">" + nextRow + "</div>");

    }

    $(".removeServiceBranch").off("click");//remove click from all "remove" links to avoid doubling up on events
    $(".removeServiceBranch").on("click", removeServiceBranch);

    return false;

}

var removeServiceBranch = function (e) {
    $(e.target).parent().parent().remove();

    return false;
}